[package]
name = "bandersnatch"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec-vrfs ={ git = "https://github.com/davxy/ark-ec-vrfs", default-features = false, features = ["bandersnatch", "ring", "parallel", "test-vectors"] }
hex = "0.4.3"

[lib]
crate-type = ["cdylib"]